version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://sitedoctor:sitedoctor_secret@postgres:5432/sitedoctor_db?schema=public
      - REDIS_URL=redis://redis:6379
      - VAULT_MASTER_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      - APP_SECRET=production-grade-super-secret-key-replace-in-env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: sitedoctor
      POSTGRES_PASSWORD: sitedoctor_secret
      POSTGRES_DB: sitedoctor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
